### ISSUE TITLE
incompatible types: cfml.parsing.cfscript.CFIdentifier cannot be converted to java.lang.String

### ISSUE THREAD

**Issue by AlexanderReichl** [cflint/CFLint#178]
I'm running into this BUILD FAILURE and I can't find a solution. Tried to use several maven and several JDK versions, but run into the same error, always.

Following result using mvn clean install -X

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Program Files/CFLint-master/src/main/java/com/cflint/plugins/core/FunctionTypeChecker.java:[20,75] incompatible types: cfml.parsing.cfscript.CFIdentifier cannot be converted to java.lang.String
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:54 min
[INFO] Finished at: 2016-06-14T13:25:08+02:00
[INFO] Final Memory: 22M/145M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project CFLint: Compilation failure
[ERROR] /C:/Program Files/CFLint-master/src/main/java/com/cflint/plugins/core/FunctionTypeChecker.java:[20,75] incompatible types: cfml.parsing.cfscript.CFIdentifier cannot be converted to java.lang.String
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project CFLint: Compilation failure
/C:/Program Files/CFLint-master/src/main/java/com/cflint/plugins/core/FunctionTypeChecker.java:[20,75] incompatible types: cfml.parsing.cfscript.CFIdentifier cannot be converted to java.lang.String

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/C:/Program Files/CFLint-master/src/main/java/com/cflint/plugins/core/FunctionTypeChecker.java:[20,75] incompatible types: cfml.parsing.cfscript.CFIdentifier cannot be converted to java.lang.String

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:911)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ryaneberly** [comment]
Do you have the latest pull from the master or dev branches.  I think one
commit was broken, but that has been fixed.

**Comment by AlexanderReichl** [comment]
Yes, I downloaded from the latest master branch yesterday.

**Comment by AlexanderReichl** [comment]
I tried the DEV branch. After mvn clean install it goes much further, than using the master branch. But towards the end I receive following error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:22 min
[INFO] Finished at: 2016-06-14T16:23:31+02:00
[INFO] Final Memory: 26M/243M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project CFLint: There are test failures.
[ERROR]
[ERROR] Please refer to D:\projects\CFLint\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by AlexanderReichl** [comment]
I tried following maven versions:

    apache-maven-3.3.3
    apache-maven-3.3.9
 
and followin JDK versions:

    jdk1.8.0_45
    jdk1.8.0_92
    jdk1.8.0_91

**Comment by ryaneberly** [comment]
Thanks, I'll take a look tonight.

On Tue, Jun 14, 2016 at 10:28 AM, Alexander Reichl <notifications@github.com

**Comment by AlexanderReichl** [comment]
Thank you.

**Comment by AlexanderReichl** [comment]
Hey there,

did you get the chance to take a look over it? 

greetings

**Comment by orcpac7** [comment]
Also tried master and dev versions today using Maven 3.3.9 and jdk1.8.0_92, ended with reference to http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ryaneberly** [comment]
I did take a brief look last night.  I get a broken build on the command line, but only a failed test in eclipse.  Still trying to figure that one out.

**Comment by ryaneberly** [comment]
try it now.   I fixed the failing test in dev and merged the dev branch to master.

**Comment by orcpac7** [comment]
Fetched master, and it compiled fine and ran! Many thanks @ryaneberly !
FYI, this in a Windows 7 enterprise environment, locked down with only local admin rights...

**Comment by ryaneberly** [comment]
Great.  thanks!

**Comment by AlexanderReichl** [comment]
Hey there and many thanks for providing a new master with fixes, but unfortunately, I'm still receiving a "BUILD FAILURE", as follows:

[DEBUG] incrementalBuildHelper#beforeRebuildExecution
[INFO] Compiling 70 source files to D:\projects\CFLint\target\classes
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/projects/CFLint/src/main/java/com/cflint/plugins/core/FunctionTypeChecker.java:[20,75] incompatible types: cfml.parsing.cfscript.CFIdentifier cannot be converted to java.lang.String
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:47 min
[INFO] Finished at: 2016-06-20T13:17:02+02:00
[INFO] Final Memory: 23M/244M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project CFLint: Compilation failure
[ERROR] /D:/projects/CFLint/src/main/java/com/cflint/plugins/core/FunctionTypeChecker.java:[20,75] incompatible types: cfml.parsing.cfscript.CFIdentifier cannot be converted to java.lang.String
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project CFLint: Compilation failure
/D:/projects/CFLint/src/main/java/com/cflint/plugins/core/FunctionTypeChecker.java:[20,75] incompatible types: cfml.parsing.cfscript.CFIdentifier cannot be converted to java.lang.String

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/D:/projects/CFLint/src/main/java/com/cflint/plugins/core/FunctionTypeChecker.java:[20,75] incompatible types: cfml.parsing.cfscript.CFIdentifier cannot be converted to java.lang.String

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:911)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by AlexanderReichl** [comment]
Hey thank you so much. It works now for me, too!
