### ISSUE TITLE
ARG_VAR_MIXED reports the wrong line number

### ISSUE THREAD

**Issue by zspitzer** [cflint/CFLint#471]
Using CFLint with Sublimelinter, when there are mixed references to variables in the arguments scope, the highlighted row isn't the first conflicting use, but following conflict.

![image](https://user-images.githubusercontent.com/426404/30572035-b5b44f5a-9d2e-11e7-874d-56f68123c83e.png)

I'd expect line 6 to be highlighted, rather than line 7

[CFlintTestCase.cfc.txt](https://github.com/cflint/CFLint/files/1312777/CFlintTestCase.cfc.txt)

**Comment by ryaneberly** [comment]
fixed in dev

**Comment by KamasamaK** [comment]
I'm not sure why it's triggering now in the first place since `event` is never declared in the local scope. It didn't trigger in 1.4.1. Also, now 4 testVarAndArgs tests are failing.

**Comment by ryaneberly** [comment]
all tests are passing in dev closing this one

**Comment by KamasamaK** [comment]
@ryaneberly Yes, tests are passing now. I'm still not sure about this rule, though. `event` was never declared as a local variable, so the issue is misleading. It seems to me that it's just complaining that the second reference is not explicitly scoped.
